import time
import os
import sys
import room2
import room4
import menu
import main

def typingPrint(text):
  for character in text:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(0.06)

def typingInput(text):
  for character in text:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(0.07)
  value = input()  
  return value  

def clear_console():
    os.system('clear')

#Options of what people can answer
answer_1 = ["1", "ONE", "one","Door 1","door 1"]
answer_2 = ["2", "TWO", "two","Door 2", "door 2"]
answer_A = ["A", "a"]
answer_B = ["B", "b"]

#For if people type things not required/in the system
required = ("I'm sorry, I don't understand what you want to do. Please choose one of the options provided. \n\n")

#Room 1
def room_1():
  time.sleep(1)
  typingPrint('You open a door to find yourself in room 1! Would you like to: ')
  time.sleep(1)
  print("""\n A. Play a Game
 B. Go to MENU""")
  choice = input('>>> ')
  if choice in answer_A:
    time.sleep(1)
    clear_console()
    rock_paper_scissors()

  elif choice in answer_B:
    time.sleep(1)
    clear_console()
    menu.menu()

  else:
    typingPrint(required)
    time.sleep(1.5)
    clear_console()
    room_1()

    
#Mini Game for room_1
def rock_paper_scissors():
  typingPrint("The game for this room is Rock, Paper, Scissors! ")
  time.sleep(0.5)
  typingPrint("If you win, you get to open one of the doors. However, if you lose, you die.")
  time.sleep(1.5)
  typingPrint("\n\n*Note: The output is predetermined not autogenerated")
  time.sleep(2)
  clear_console()
  typingPrint("Are you ready? ")
  time.sleep(1)
  typingPrint("3..")
  time.sleep(1)
  typingPrint("2..")
  time.sleep(1)
  typingPrint("1..")
  time.sleep(1)
  choice = input('\nEnter Choice (r/p/s) >>> ')
  
  if choice == 'r':
    print("\nScissors! ")
    time.sleep(1)
    typingPrint("Aw man, you got me! ")
    time.sleep(0.5)
    typingPrint("I must say, not bad for your first game! I respectfully admit my defeat :( ")
    time.sleep(1)
    room_1_doors()

  if choice == 'p':
    print("\nScissors! ")
    time.sleep(1)
    typingPrint("Oh... ")
    time.sleep(0.5)
    typingPrint("this was quite unexpected.")
    time.sleep(1)
    typingPrint(" You lost quicker than I thought... :(")
    time.sleep(1.5)
    typingPrint("\n\nWell it was fun I guess. ")
    time.sleep(0.5)
    typingPrint("GOODBYE!")
    time.sleep(2)
    clear_console()
    typingPrint("*Paper towels start flowing into the room. Under less than a minute, it wraps around your whole body and face – on the outside, you look like a big ball of paper towels. As you try to breathe for oxygen, you realise there is no airhole and collaspe on the floor*")
    time.sleep(1)
    typingPrint("\n\nYOU DIED")
    time.sleep(2)
    clear_console()
    typingPrint("Thank you for Playing!")
    time.sleep(2)
    main.restart()

  if choice == 's':
    typingPrint("\nScissors! ")
    time.sleep(1)
    typingPrint("Woah it's a tie! ")
    time.sleep(1)
    typingPrint("Usually we would play again, ")
    time.sleep(0.5)
    typingPrint("but because I see potentional in you young player, ")
    time.sleep(0.5)
    typingPrint("I'll let you off the hook just this once since we have many more games in store for you :D. \n\n")
    time.sleep(1)
    room_1_doors()

  else:
    typingPrint(required)
    time.sleep(1.5)
    clear_console()
    rock_paper_scissors()

    
#Door options for room_1
def room_1_doors():
    typingPrint("Don't celebrate just yet though! ")
    time.sleep(0.5)
    typingPrint("Because now, you need to choose which door you want to go through:")
    time.sleep(0.5)
    print("""\n Door 1. Located on your right
 Door 2. Located straight ahead""")
    time.sleep(0.5)
    typingPrint("\nWhich door do you wish to go through? ")
    choice = input(">>> ")
    if choice in answer_1:
      time.sleep(1)
      room2.room_2()

    elif choice in answer_2:
      time.sleep(1)
      room4.room_4()
    
    else:
      typingPrint(required)
      time.sleep(1.5)
      room_1_doors()